<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Provides JSON5 syntax highlighting for Visual Studio.
     Copy into %USERPROFILE%/.vs/Extensions/json5/Syntaxes/
-->
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>JSON5</string>
    <key>scopeName</key>
    <string>source.json5</string>
    <key>uuid</key>
    <string>f91d22ce-2aef-473a-a4a8-d047b73b2cd0</string>
    <key>fileTypes</key>
    <array>
      <string>json5</string>
    </array>
    <key>foldingStartMarker</key>
    <string>(?x)
      ^        # a line beginning with
      \s*      # some optional space
      [{\[]    # the start of an object or array
      (?!      # but not followed by
        .*     # whatever
        [}\]]  # and the close of an object or array
        ,?     # an optional comma
        \s*    # some optional space
        $      # at the end of the line
      )
      |        # ...or...
      [{\[]    # the start of an object or array
      \s*      # some optional space
      $        # at the end of the line</string>
    <key>foldingStopMarker</key>
    <string>(?x)
      ^      # a line beginning with
      \s*    # some optional space
      [}\]]  # and the close of an object or array</string>
    <key>keyEquivalent</key>
    <string>^~J</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#value</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>array</key>
      <dict>
        <key>name</key>
        <string>meta.structure.array.json5</string>
        <key>begin</key>
        <string>\[</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\]</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.array.end.json5</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#value</string>
          </dict>
          <dict>
            <key>name</key>
            <string>punctuation.separator.array.json5</string>
            <key>match</key>
            <string>,</string>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.expected-array-separator.json5</string>
            <key>match</key>
            <string>[^\s\]]</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.documentation.json5</string>
            <key>begin</key>
            <string>/\*\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json5</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.json5</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json5</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.js</string>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.json5</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>constant</key>
      <dict>
        <key>name</key>
        <string>constant.language.json5</string>
        <key>match</key>
        <string>\b(?:true|false|null)\b</string>
      </dict>
      <key>number</key>
      <dict>
        <key>match</key>
        <string>[+-]?(?:Infinity|NaN|0[xX][0-9a-fA-F]+|0[bB][01]+|(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[eE][+-]?[0-9]+)?)</string>
        <key>name</key>
        <string>constant.numeric.json5</string>
      </dict>
      <key>object</key>
      <dict>
        <key>begin</key>
        <string>\{</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.dictionary.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\}</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.dictionary.end.json5</string>
          </dict>
        </dict>
        <key>name</key>
        <string>meta.structure.dictionary.json5</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>comment</key>
            <string>the JSON5 object key</string>
            <key>include</key>
            <string>#quotedobjectkey</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>the JSON5 object key</string>
            <key>include</key>
            <string>#rawobjectkey</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>name</key>
            <string>meta.structure.dictionary.value.json5</string>
            <key>begin</key>
            <string>:</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.dictionary.key-value.json5</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(,)|(?=\})</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>punctuation.separator.dictionary.pair.json5</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>comment</key>
                <string>the JSON5 object value</string>
                <key>include</key>
                <string>#value</string>
              </dict>
              <dict>
                <key>name</key>
                <string>invalid.illegal.expected-dictionary-separator.json5</string>
                <key>match</key>
                <string>[^\s,]</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>invalid.illegal.expected-dictionary-separator.json5</string>
            <key>match</key>
            <string>[^\s\}]</string>
          </dict>
        </array>
      </dict>
      <key>quotedobjectkey</key>
      <dict>
        <key>name</key>
        <string>support.type.property-name.json5</string>
        <key>begin</key>
        <string>("|')</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.support.type.property-name.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.support.type.property-name.end.json5</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#stringcontent</string>
          </dict>
        </array>
      </dict>
      <key>rawobjectkey</key>
      <dict>
        <key>name</key>
        <string>support.type.property-name.json5</string>
        <key>begin</key>
        <string>[^\d\s,:/{}\[\]]</string>
        <key>end</key>
        <string>(?=:)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\(?:u\{[0-9a-fA-F]+\}|u[0-9a-fA-F]{4})</string>
            <key>name</key>
            <string>constant.character.escape.json5</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>invalid.illegal.unrecognized-property-name-escape.json5</string>
          </dict>
        </array>
      </dict>
      <key>string</key>
      <dict>
        <key>name</key>
        <string>string.quoted.json5</string>
        <key>begin</key>
        <string>("|')</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.begin.json5</string>
          </dict>
        </dict>
        <key>end</key>
        <string>\1</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.string.end.json5</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#stringcontent</string>
          </dict>
        </array>
      </dict>
      <key>stringcontent</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>invalid.illegal.unrecognized-string-escape.json5</string>
            <key>match</key>
            <string>\\[1-9]</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.character.escape.json5</string>
            <key>match</key>
            <string>\\(?:u\{[0-9a-fA-F]+\}|u[0-9a-fA-F]{4}|x[0-9a-fA-F]{2}|.|$)</string>
          </dict>
        </array>
      </dict>
      <key>value</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#constant</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#number</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#string</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#array</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#object</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
